### ISSUE TITLE
Need to access this repos contentful data 

### ISSUE THREAD

**Issue by kaleem-elahi** [alexanderalmstrom/alexanderalmstrom.com#1]
Hi @alexanderalmstrom 

I wanted an exmaple of code which you have written, Un fortunately i am getting error of Authentication. Screenchot attached (Can you pls help me fix this issue)

![image](https://user-images.githubusercontent.com/10118543/182347909-b4db5783-ab65-4b10-9a6f-0feee28b6ab6.png)

**Comment by alexanderalmstrom** [comment]
Sorry. I'm not giving away my Contentful API credentials.
